import enumList from '../utils/enum-list';

const Progress = enumList({
  type: 'progress',
  values: {
    INBOX: 100,
    NOT_STARTED: 110,
    SCHEDULED: 120,
    ASSIGNED: 130,
    IN_PROGRESS: 200,
    SENT: 210,
    REVIEWED: 220,
    PENDING: 300,
    MISSING_INFORMATION: 310,
    NEED_FIXING: 320,
    DONE: 500,
    ERROR: 400,
    REJECTED: 410,
    LATE: 420,
    CANCELED: 600,
    CLOSED: 610,
  },
  colors: {
    INBOX: 'neutral.300',
    NOT_STARTED: 'neutral.300',
    SCHEDULED: 'neutral.300',
    ASSIGNED: 'neutral.300',
    IN_PROGRESS: 'info',
    SENT: 'info',
    REVIEWED: 'info',
    PENDING: 'warning',
    MISSING_INFORMATION: 'warning',
    NEED_FIXING: 'warning',
    DONE: 'success',
    ERROR: 'error',
    REJECTED: 'error',
    LATE: 'error',
    CANCELED: 'neutral.300',
    CLOSED: 'neutral.300',
  },
  labels: {
    fr: {
      INBOX: 'Inbox',
      NOT_STARTED: 'Not started',
      SCHEDULED: 'Scheduled',
      ASSIGNED: 'Assigned',
      IN_PROGRESS: 'In progress',
      SENT: 'Sent',
      REVIEWED: 'Reviewed',
      PENDING: 'Pending',
      MISSING_INFORMATION: 'Missing information',
      NEED_FIXING: 'Need fixing',
      DONE: 'Done',
      ERROR: 'Error',
      REJECTED: 'Rejected',
      LATE: 'Late',
      CANCELED: 'Canceled',
      CLOSED: 'Closed',
    },
  },
});

export default Progress;
