export const RARITIES = [
  { value: 1, name: 'Common', group: 7 },
  { value: 2, name: 'Secret Rare', group: 3 },
  { value: 3, name: 'Ultra Rare', group: 4 },
  { value: 4, name: 'Super Rare', group: 5 },
  { value: 5, name: 'Rare', group: 6 },
  { value: 6, name: 'Ultimate Rare', group: 2 },
  { value: 7, name: 'Uncommon' },
  { value: 8, name: 'Special Rare' },
  { value: 9, name: 'Holo Rare' },
  { value: 10, name: 'Gold Rare', group: 2 },
  { value: 11, name: 'Promo' },
  { value: 12, name: 'Ghost Rare', group: 1 },
  { value: 13, name: 'Starfoil Rare', group: 1 },
  { value: 14, name: 'Starter Rare' },
  { value: 15, name: 'Platinum Rare', group: 1 },
  { value: 16, name: 'Gold Secret Rare', group: 1 },
  { value: 17, name: 'Feature Rare' },
  { value: 18, name: 'Expansion Rare' },
  { value: 19, name: 'Token', group: 8 },
  { value: 20, name: 'Unknown2' },
  { value: 21, name: 'Online Code Card' },
  { value: 22, name: 'Collectors Rare', group: 1 },
  { value: 23, name: 'Mosaic Rare', group: 1 },
  { value: 24, name: 'Special', group: 9 },
  { value: 25, name: 'Shatterfoil', group: 1 },
  { value: 26, name: 'Oversized', group: 9 },
  { value: 27, name: 'Starlight Rare', group: 1 },
  { value: 28, name: 'Amazing Rare' },
  { value: 29, name: 'Land' },
  { value: 30, name: 'Mythic' },
  { value: 31, name: 'Code Card' },
  { value: 32, name: 'Tip Card' },
  { value: 33, name: 'Time Shifted' },
  { value: 34, name: 'Masterpiece' },
  { value: 35, name: 'Unknown', group: 9 },
  { value: 36, name: 'Fixed' },
  { value: 37, name: 'Double Rare' },
  { value: 38, name: 'Triple Rare' },
  { value: 40, name: 'Magic Stone' },
  { value: 41, name: 'Loot' },
  { value: 42, name: 'Epic' },
  { value: 43, name: 'Normal' },
  { value: 44, name: 'Trial Deck' },
  { value: 45, name: 'Climax Rare' },
  { value: 46, name: 'Climax Common' },
  { value: 47, name: 'Marvel Rare' },
  { value: 48, name: 'Hero' },
  { value: 49, name: 'Legend' },
  { value: 50, name: 'Starter' },
  { value: 51, name: 'Special Parallel' },
  { value: 52, name: 'Legion Rare' },
  { value: 53, name: 'Generation Rare' },
  { value: 54, name: 'Super Generation Rare' },
  { value: 55, name: 'Wedding Special Parallel' },
  { value: 56, name: 'Rummy Labyrinth Rare' },
  { value: 57, name: 'Z Rare' },
  { value: 58, name: 'Vilest Delete Rare' },
  { value: 59, name: 'Special Vanguard Rare' },
  { value: 60, name: 'Origin Rare' },
  { value: 61, name: 'Image Ride Rare' },
  { value: 62, name: 'Vanguard Rare' },
  { value: 63, name: 'Holo Rare Common' },
  { value: 64, name: 'Delete Rare' },
  { value: 65, name: 'Super Special Parallel' },
  { value: 66, name: 'Legend Idol Rare' },
  { value: 67, name: 'Twin Vanguard Rare' },
  { value: 68, name: 'Super Special Rare' },
  { value: 69, name: 'Original Costume Rare' },
  { value: 70, name: 'Holo' },
  { value: 71, name: 'Over RR' },
  { value: 72, name: 'Oversize' },
  { value: 73, name: 'Legendary' },
  { value: 74, name: 'Extra Rare' },
  { value: 75, name: 'Parallel Foil' },
  { value: 76, name: 'Gun Gale Rare' },
  { value: 77, name: 'High Rare' },
  { value: 78, name: 'Special Member' },
  { value: 79, name: 'Band Rare' },
  { value: 80, name: 'JoJo Rare' },
  { value: 81, name: 'Fujimi Bunko Rare' },
  { value: 82, name: 'Kaguya Rare' },
  { value: 83, name: 'Foil' },
  { value: 84, name: 'Royal Rare' },
  { value: 85, name: 'Staple Resource' },
  { value: 86, name: 'Faction' },
  { value: 87, name: 'Uber' },
  { value: 88, name: 'Premium Gold Rare', group: 1 }
];

export const RARITIES_BY_VALUE = RARITIES.reduce((acc, rarity) => {
  acc[`${rarity.value}`] = rarity;
  return acc;
}, {});
